[package]
name = "resp-result"
version = "0.2.3"
edition = "2021"
authors = ["FrozenString<frozenstringstable@gmail.com>"]
description = "Help Struct For Axum or Actix Response"
homepage = "https://github.com/Goodjooy/resp-result"
documentation = "https://docs.rs/resp-result"
license = "MIT"

[package.metadata.docs.rs]
features = ["axum-full"]
rustdoc-args = ["--cfg", "docsrs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = []
axum-full = ["log", "extra-code", "for-axum"]
actix-full = ["log", "extra-code", "for-actix"]
log = ["logger"]
extra-code = []
extra-resp = []
for-axum = ["axum", "mime", "extra-resp"]
for-actix = ["actix-web", "mime", "extra-resp"]
for-rocket = []

[dependencies]
state = "0.5"
serde_json = "1"
http = "0.2"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.logger]
optional = true
package = "log"
version = "0.4"

[dependencies.axum]
optional = true
version = "0.5"

[dependencies.actix-web]
optional = true
version = "^4"

[dependencies.mime]
version = "0.3"
optional = true

[dev-dependencies]
serde_json = "1"
tokio = { version = "1", features = ["full"] }
