[package]
name = "resp-result"
version = "0.4.0"
edition = "2021"
authors = ["FrozenString<frozenstringstable@gmail.com>"]
description = "Help Struct For Axum or Actix Response"
homepage = "https://github.com/Goodjooy/resp-result"
documentation = "https://docs.rs/resp-result"
license = "MIT"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs", "--cfg", "doc_cfg"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[features]
default = ["axum-full"]
axum-full = ["log", "extra-error", "for-axum"]
actix-full = ["log", "extra-error", "for-actix"]
log = ["logger"]
extra-error = []
for-axum = ["axum"]
for-actix = ["actix-web"]

[dependencies]
serde_json = "1"
http = "0.2"
once_cell = "1"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.logger]
optional = true
package = "log"
version = "0.4"

[dependencies.axum]
optional = true
version = "0.5"

[dependencies.actix-web]
optional = true
version = "^4"

[dependencies.mime]
version = "0.3"

[dev-dependencies]
serde_json = "1"
tokio = { version = "1", features = ["full"] }
